### ISSUE TITLE
Move core to separate repo

### ISSUE THREAD

**Issue by szepeviktor** [o10n-x/wordpress-cloudfront-page-cache#2]
@optimalisatie Please consider moving [core](https://github.com/o10n-x/wordpress-cloudfront-page-cache/tree/master/core) *and aws-sdk too* to a separate repo
and using it here as a [submodule](https://git-scm.com/docs/git-submodule)

**Comment by szepeviktor** [comment]
Using composer for aws-sdk is the optimal solution and of course adding `/vendor` to .gitignore.

**Comment by optimalisatie** [comment]
Hi!

Thanks a lot for the suggestion to use a GitHub submodule! 

We've tried it however it doesn't seem to be compatible with WordPress Github Updater.

> Submodules will not install. This is a longstanding issue and one that cannot be worked around.
> 
> You can create a release asset that separately contains the entire project. Please see wiki.

https://github.com/afragen/github-updater/issues/516

If you have an alternative suggestion, please let us know!

**Comment by szepeviktor** [comment]
OK, I see.

I've opened this issue because the less files the better.

**Comment by szepeviktor** [comment]
@optimalisatie although you may have a *dumping ground* master branch and a proper develop branch.

**Comment by szepeviktor** [comment]
I would make your core plugin also a public composer package and all would be a simple composer.json file.

**Comment by optimalisatie** [comment]
Thanks a lot for your feedback! It is very valuable for the project!

In regards to the plugin core, it's not really a plugin but more like a component that is shared by multiple plugins. 

For performance reasons, the core to be used by all optimization plugins is selected at random based on first come first served (WordPress plugin execution order). Once selected, all optimization plugins add it's functionality to the loaded core.

The plugin core manages the output buffer and what's specifically important of the setup is that it manages Google Closure Compiler pre-compiled Javascript client modules. 

All optimization plugins can add javascript client functionality that reuses independently compiled parts of other modules. It thereby enables to concatenate Javascript modules as raw Javascript code (without a module loader). This enables to save every tiny byte that could be saved in the javascript client, while enabling unlimited extensibility and the best Javascript performance (parse and execution speed optimized by [Google Closure Compiler](https://developers.google.com/closure/compiler/)).

Example: the following two independent javascript files can be merged together without overhead:

https://github.com/o10n-x/wordpress-o10n-core/blob/master/public/js/timed-exec.js

https://github.com/o10n-x/wordpress-javascript-optimization/blob/master/public/js/js.js

With 15-20 javascript modules, it will save 20x the code that a module loader would normally consume (e.g. `M(function(x,y,z){...});`) + there is no parse and execution overhead.

The setup also enables to secure a website with a strict Content Security Policy while enabling the latest frontend optimization technologies.

The client configuration uses a compressed JSON format.

```html
<script data-o10n="[[ø],ø,[[["0|1|8",false]],1,ø:5,µ,ø:3,1],[[["0|1|12"]],ø,ø,[21],ø,1,ø,µ,ø,ø,3600,1],["\/o10n-sw.js","\/",µ,ø,-1,1]]">
```

It may appear to be complex and difficult to manage, but the plugin simply intends to achieve the ultimate website performance result without concessions for easy maintenance.
